package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 09 19:14:31 CEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NodesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NodesVOImpl() {
    }
}

